export const POST_MAIL_CONTACT_US_REQUEST = 'POST_MAIL_CONTACT_US_REQUEST'
export const POST_MAIL_CONTACT_US_SUCCESS = 'POST_MAIL_CONTACT_US_SUCCESS'
export const POST_MAIL_CONTACT_US_FAILURE = 'POST_MAIL_CONTACT_US_FAILURE'
export const POST_MAIL_CONTACT_US_CLEAR = 'POST_MAIL_CONTACT_US_CLEAR'

export const USER_AGENT= 'USER_AGENT'
